version: 1.0.{build}
os: Visual Studio 2017
init:
- git config --global core.autocrlf true
before_build:
- nuget restore
build:
  project: PublicApiAnalyzer.sln
  verbosity: minimal
test_script:
- .\packages\OpenCover.4.6.247-rc\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\publicapianalyzer\PublicApiAnalyzer\PublicApiAnalyzer.Test\bin\Debug\net452\PublicApiAnalyzer.Test.dll -noshadow -appveyor" -returntargetcode -filter:"+[PublicApi*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\PublicApiAnalyzer_coverage.xml
- .\packages\Codecov.1.0.1\tools\codecov.exe -f "PublicApiAnalyzer_coverage.xml"
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
artifacts:
- path: 'PublicApiAnalyzer\**\*.vsix'
- path: 'PublicApiAnalyzer\**\*.nupkg'
